config/routes.rb
Rails.application.routes.draw do
  post '/submit', to: 'words#submit'

  root 'words#index'
end

app/models/word.rb
class Word < ActiveRecord::Base
  def read_points
    (Time.now.utc.to_date - self.read_last_date.to_date).to_i
  end

  def write_points
    (Time.now.utc.to_date - self.write_last_date.to_date).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index

  end

  def submit
    words = JSON.parse(params["words"])
    words.each do |word|
      w = Word.find_by!(name: word["name"])
      if word["mode"] == 0
        w.read_last_date = word["points"].days.ago
      else
        w.write_last_date = word["points"].days.ago
      end
      w.save!
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Japanese</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/words/index.html.erb
<div id="wrapper">
  <div id="score">Score: <span id="score-val">0/0</span></div>
  <div id="top-bar">
    <%= form_tag submit_path do %>
        <%= hidden_field_tag :words %>
        <%= submit_tag "Save" %>
    <% end %>
  </div>
  <div class="clear"></div>
  <div id="main"></div>
</div>
<div id="before" class="footer">
  <div id="skip" class="button" onclick="skip()">Skip</div>
  <div id="check" class="button" onclick="check()">Check</div>
  <div class="clear"></div>
</div>
<div id="after" class="footer hidden">
  <div id="right" class="button" onclick="right()">Right</div>
  <div id="wrong" class="button" onclick="wrong()">Wrong</div>
  <div class="clear"></div>
</div>
<script>
  right_push_days = -5;
  current_index = 0;
  mode = 0;
  score = 0;
  total = 0;

  function init() {
    words = [];

    <% Word.all.order(read_last_date: :asc).each do |word| %>
    words.push({
      name: "<%= word.name %>",
      sound: "<%= word.sound %>",
      definition: "<%= word.definition %>",
      points: <%= word.read_points %>,
      mode: 0
    });
    <% end %>

    <% Word.all.order(write_last_date: :asc).each do |word| %>
    words.push({
      name: "<%= word.name %>",
      sound: "<%= word.sound %>",
      definition: "<%= word.definition %>",
      points: <%= word.write_points %>,
      mode: 1
    });
    <% end %>

    words = shuffle(words);

    words.sort(function(word1, word2) { return word2["points"] - word1["points"]});

    write(words);

    $('#main').text(words[current_index]["name"]);
  }

  function skip() {
    words = read();

    words[current_index]["points"] = right_push_days;

    write(words);

    nextPage()
  }

  function check() {
    words = read();

    $('#main').text(format(words[current_index]));

    after();
  }

  function nextPage() {
    words = read();

    current_index++;

    if (current_index >= words.length) {
      current_index = 0;
      score = 0;
      total = 0;
      words.sort(function(word1, word2) { return word2["points"] - word1["points"]});
    }

    write(words);

    if (words[current_index]["mode"] == 0) {
      $('#main').text(words[current_index]["name"]);
    } else {
      $('#main').text(words[current_index]["definition"]);
    }

    before();
    updateScore();
  }

  function wrong() {
    words = read();

    words[current_index]["points"] = 0;
    total++;

    write(words);

    nextPage();
  }

  function right() {
    words = read();

    words[current_index]["points"] = right_push_days;
    total++;
    score++;

    write(words);

    nextPage();
  }

  function before() {
    $('#before').removeClass("hidden");
    $('#after').addClass("hidden");
  }

  function after() {
    $('#before').addClass("hidden");
    $('#after').removeClass("hidden");
  }

  function updateScore() {
    $('#score-val').text(score + "/" + total);
  }

  function write(obj) {
    $('#words').val(JSON.stringify(obj));
  }

  function read() {
    return JSON.parse($('#words').val());
  }

  function format(word_obj) {
    if (word_obj["name"] == word_obj["sound"]) {
      return word_obj["name"] + ": " + word_obj["definition"]
    } else {
      return word_obj["name"] + " (" + word_obj["sound"] + "): " + word_obj["definition"]
    }
  }

  function shuffle(array) {
    var currentIndex = array.length, temporaryValue, randomIndex;

    // While there remain elements to shuffle...
    while (0 !== currentIndex) {

      // Pick a remaining element...
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex -= 1;

      // And swap it with the current element.
      temporaryValue = array[currentIndex];
      array[currentIndex] = array[randomIndex];
      array[randomIndex] = temporaryValue;
    }

    return array;
  }

  init();
</script>

app/views/words/submit.html.erb
<a href="/"><div id="submitted">Submitted</div></a>